language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script:
  - mvn test

deploy:
  provider: script
  script: mvn deploy -s settings.xml -DskipTests -DBintrayKey=$BintrayKey -B
  on:
    tags: true